name: Skykit calendar Deploy job

on:
  push:
    branches:
      - "main"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install dependencies and configure git
        run: npm install

      - name: Configuring Git
        run: |
          git config --global user.email "cd@skykit.com"
          git config --global user.name "Github actions"

      - name: Creating release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git stash
          npm run release

      - name: Changelog
        run: cat CHANGELOG.md
        
