name: Skykit calendar Deploy job

on:
  push:
    branches:
      - "master"

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12'

      - name: Install dependencies and configure git
        run: npm install

      - name: Configuring Git
        run: |
          git config --global user.email "cd@skykit.com"
          git config --global user.name "Github actions"

      - name: Creating release
        run: |
          git stash
          npm run release
          cat CHANGELOG.md

      - name: Pushing new release
        run: |
          git commit -am '[CD] Auto-release'
          git push origin main
