name: Skykit calendar Deploy job

on:
  push:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install dependencies
        run: npm i
      - name: release
        run: npm run release
      - run: cat CHANGELOG.md